### ISSUE TITLE
 Configuration invalid Platform not found: sensor.open_route_service

### ISSUE THREAD

**Issue by Langtonpaul** [eifinger/open_route_service#2]
Hi can you help I cant seem to get around the issue of

Configuration invalid
Platform not found: sensor.open_route_service
I installed via Hab but copy and pasted raw files again from gitHub
running Home Assistant
0.96.3

Thanks

**Comment by eifinger** [comment]
Hi,
could you please use the template provided when you open a new issue?

I need mote information like the configuration you used.

**Comment by Langtonpaul** [comment]
Hi thanks for your reply sorry not used this platform before where do I find the template.

**Comment by eifinger** [comment]
https://github.com/eifinger/open_route_service/issues/new?template=issue.md

**Comment by Langtonpaul** [comment]
Ok so not sure how to get any more info hope this helps. Thanks
Home Assistant 0.96.3

## Version of the custom_component
Installed version: v1.0.1

## Configuration

```yaml
 - platform: open_route_service
    api_key: "5b3ce3597851110001cf6248272etc,etc"
    origin_latitude: "51.222975"
    origin_longitude: "9.267577"
    destination_latitude: "51.257430"
    destination_longitude: "9.335892" 
Add your logs here.

```

## Describe the bug
I get this message when I do a config check.

Configuration invalid
Platform not found: sensor.open_route_service


## Debug log
Error scanning devices
7:28 PM components/bt_home_hub_5/device_tracker.py (WARNING) - message first occured at 4:25 PM and shows up 857 times
Error doing job: Task exception was never retrieved
7:28 PM core.py (ERROR) - message first occured at 4:25 PM and shows up 356 times
Error rendering info template expected token 'end of statement block', got 'version_installed'
7:27 PM custom_components/hacs/handler/logger.py (WARNING) - message first occured at 4:26 PM and shows up 7 times
Update of switch.012001485ccf7f512ada is taking over 10 seconds
7:19 PM __main__.py (WARNING)
Unable to retrieve data
6:55 PM components/scrape/sensor.py (ERROR) - message first occured at 6:07 PM and shows up 2 times
Error fetching data: <PreparedRequest [GET]> from https://www.severn-bore.co.uk/2019_times.html failed with HTTPSConnectionPool(host='www.severn-bore.co.uk', port=443): Max retries exceeded with url: /2019_times.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f72ebf30510>: Failed to establish a new connection: [Errno -3] Try again'))
6:55 PM components/rest/sensor.py (ERROR)
Error fetching data: <PreparedRequest [GET]> from https://www.severn-bore.co.uk/2019_times.html failed with HTTPSConnectionPool(host='www.severn-bore.co.uk', port=443): Max retries exceeded with url: /2019_times.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f72ec8fead0>: Failed to establish a new connection: [Errno -3] Try again'))
6:07 PM components/rest/sensor.py (ERROR)
Update of sensor.social_energy is taking over 10 seconds
5:40 PM __main__.py (WARNING)
Could not read state for 192.168.1.106: Communication error
5:33 PM components/tplink/switch.py (WARNING) - message first occured at 5:02 PM and shows up 2 times
Unable to connect to Google, using cached data
5:26 PM components/google/calendar.py (WARNING)
Connection to the router timed out
5:07 PM /usr/local/lib/python3.7/site-packages/bthomehub5_devicelist/bthomehub5_devicelist.py (ERROR)
Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password
4:49 PM components/http/__init__.py (WARNING) - message first occured at 4:36 PM and shows up 2 times
YAML file /config/themes/jade.yaml contains duplicate key "label-badge-background-color". Check lines 9 and 33.
4:49 PM util/yaml/loader.py (ERROR) - message first occured at 4:36 PM and shows up 2 times
You are using a custom integration for open_route_service which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
4:36 PM loader.py (WARNING)
Update of sensor.hacs is taking over 10 seconds
4:27 PM __main__.py (WARNING)
Error doing job: Task exception was never retrieved
4:25 PM helpers/entity_platform.py (ERROR) - message first occured at 4:25 PM and shows up 66 times
Error doing job: Task exception was never retrieved
4:25 PM helpers/entity.py (ERROR) - message first occured at 4:25 PM and shows up 69 times
Setup of platform command_line is taking over 10 seconds.
4:25 PM __main__.py (WARNING)
Error setting up platform legacy
4:25 PM components/bluetooth_tracker/device_tracker.py (ERROR)

```text

Add your logs here.

```

**Comment by eifinger** [comment]
Does this error just appear when you do a config check or did you restart homeassistant and get this error in the error log.

The config check does throw errors for custom_components on homeassistant versions < 0.97. The component should work nonetheless

**Comment by Langtonpaul** [comment]
It appears when I do a config check. HA wont restart via the restart button if there is an error, I will try a manual restart.

**Comment by Langtonpaul** [comment]
ok so i have it working now. Thank you for your support.
