### ISSUE TITLE
Deprecated properties used in Home Assisant

### ISSUE THREAD

**Issue by screenagerbe** [eifinger/open_route_service#221]
## Version of the custom_component
latest (1.1.1)

## Configuration

Add your configuration here.
N/A

## Describe the bug
It's more like a warning, but it will become a bug from January 2023 onwards.
``` Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 13:53:16 (1 occurrences)
Last logged: 13:53:16
Detected integration that accesses the `name` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for open_route_service using this method at custom_components/open_route_service/sensor.py, line 157: config.get(CONF_UNIT_SYSTEM, hass.config.units.name),
```

## Debug log

Add your logs here.

N/A

**Comment by CloCkWeRX** [comment]
Added details of what would need to be adjusted via #233

**Comment by eifinger** [comment]
I decided to longer maintain this component. I currently do not have enough free time I want to spend on it.

My decision is based on the fact, that I don't see an added benefit of this integration over waze, google or here.

* Has a higher entry barrier as waze as it needs an account to generate an API key
* Does not provide live-traffic data and going by [this](https://ask.openrouteservice.org/t/live-time-traffic/1756) post it will not have it in the near future
